SET NAMES utf8mb4;
USE proyectoweb_db;

INSERT INTO usuario (nombres, apellidos, correo, contrasena, estado, rol) VALUES ('Admin', 'Principal', 'admin@quitodescubre.ec', 'admin123', 1, 'administrador'), ('María', 'Pérez', 'maria@correo.com', 'usuario123', 1, 'usuario');

INSERT INTO categoria (nombre, descripcion, tipo) VALUES ('Histórico', 'Patrimonio e historia de la ciudad', 'Turística'), ('Naturaleza', 'Parques, miradores y aire libre', 'Turística'), ('Aventura', 'Actividades de adrenalina', 'Turística'), ('Comida típica', 'Sabores tradicionales quiteños', 'Gastronómica'), ('Cafeterías', 'Café de especialidad y postres', 'Gastronómica'), ('Restaurantes', 'Cocina nacional e internacional', 'Gastronómica'), ('Música', 'Conciertos y festivales musicales', 'Cultural'), ('Tradiciones', 'Fiestas populares y religiosas', 'Cultural'), ('Arte', 'Exposiciones y teatro', 'Cultural');

INSERT INTO elemento_contenido (tipo, nombre, descripcion, sector, calificacion_promedio, destacado, activo, categoria_id, horario, url_imagen) VALUES ('LugarTuristico', 'Centro Histórico', 'El casco colonial mejor conservado de América Latina, Patrimonio de la Humanidad.', 'Centro', 4.8, 1, 1, (SELECT id FROM categoria WHERE nombre='Histórico' AND tipo='Turística' LIMIT 1), 'Lun-Dom 08:00-18:00', 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Quito_Centro_Histórico.JPG'), ('LugarTuristico', 'Mitad del Mundo', 'Monumento y museo sobre la línea ecuatorial.', 'San Antonio', 4.6, 1, 1, (SELECT id FROM categoria WHERE nombre='Histórico' AND tipo='Turística' LIMIT 1), 'Lun-Dom 09:00-18:00', 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Mitad_del_Mundo_01.jpg'), ('LugarTuristico', 'Teleférico de Quito', 'Ascenso al volcán Pichincha con vistas panorámicas de la ciudad.', 'Cruz Loma', 4.7, 0, 1, (SELECT id FROM categoria WHERE nombre='Aventura' AND tipo='Turística' LIMIT 1), 'Lun-Dom 09:00-17:00', 'https://www.quitoinforma.gob.ec/wp-content/uploads/2023/11/3-Teleferico.png'), ('LugarTuristico', 'Parque La Carolina', 'El pulmón verde más visitado de la ciudad moderna.', 'La Carolina', 4.4, 0, 1, (SELECT id FROM categoria WHERE nombre='Naturaleza' AND tipo='Turística' LIMIT 1), 'Lun-Dom 05:00-19:00', 'https://img.goraymi.com/2018/07/24/4327da4af2dab9157642503de7aa7eb9_xl.jpg');

INSERT INTO elemento_contenido (tipo, nombre, descripcion, sector, calificacion_promedio, destacado, activo, categoria_id, especialidad, horario, url_imagen) VALUES ('EstablecimientoGastronomico', 'Hornado Doña Rosa', 'Hornado tradicional con tortillas de papa y agrio.', 'Mercado Central', 4.7, 1, 1, (SELECT id FROM categoria WHERE nombre='Comida típica' AND tipo='Gastronómica' LIMIT 1), 'Hornado quiteño', 'Mar-Dom 08:00-16:00', 'https://scontent.fuio22-1.fna.fbcdn.net/v/t39.99422-6/740343476_1662792382517948_7312048753735353408_n.png?stp=dst-jpg_tt6&cstp=mx1086x1448&ctp=s1086x1448&_nc_cat=111&ccb=1-7&_nc_sid=aa7b47&_nc_ohc=hlN28e61YpsQ7kNvwH1pjXn&_nc_oc=Adqyg7hRRxVRnky6zRmK2m10T4-Vv5J6kGdUUqX-IfgpAnIzJMhna0geAxYysyUNaL0oQm2VktU2Iru0h8kdw4OZ&_nc_zt=14&_nc_ht=scontent.fuio22-1.fna&_nc_gid=f8wq-XC9OpLbYPM5nwR_Qw&_nc_ss=7b2a8&oh=00_AQCJlCKSSK_ELM6F-GLIH3YT_CYVq08PGMBWq5rA4Uve3A&oe=6A659261'), ('EstablecimientoGastronomico', 'Café de la Ronda', 'Canelazos, empanadas de viento y música en vivo en la calle La Ronda.', 'La Ronda', 4.5, 0, 1, (SELECT id FROM categoria WHERE nombre='Cafeterías' AND tipo='Gastronómica' LIMIT 1), 'Canelazo y empanadas', 'Mié-Dom 16:00-23:00', 'https://scontent.fuio22-1.fna.fbcdn.net/v/t39.30808-6/481662495_1633210604240153_8692816742282906688_n.jpg?stp=dst-jpg_tt6&cstp=mx1440x864&ctp=s1440x864&_nc_cat=103&ccb=1-7&_nc_sid=cc71e4&_nc_ohc=SRmUmp5Z9bwQ7kNvwEi7vWY&_nc_oc=AdqscPsBSWb2sVwt0MPoDTBnBWrujb2KFQkUxvzfnM8KsHsgf93LVISF7KMNrAUbIdmvEQGRDgisd6OJV0T19WrE&_nc_zt=23&_nc_ht=scontent.fuio22-1.fna&_nc_gid=AAjHdJnVIX0zHvM_WsRUIQ&_nc_ss=7b2a8&oh=00_AQAfGgbsl0kdM_nIg0yioHYT16KW307cBu_4AS-pw0ps4g&oe=6A65AC24'), ('EstablecimientoGastronomico', 'Fritada de la Floresta', 'Fritada, mote y maduro frito al estilo tradicional.', 'La Floresta', 4.3, 0, 1, (SELECT id FROM categoria WHERE nombre='Comida típica' AND tipo='Gastronómica' LIMIT 1), 'Fritada', 'Lun-Dom 11:00-20:00', 'https://pbs.twimg.com/media/Ebc18VzXsAEEMdf.jpg');

INSERT INTO elemento_contenido (tipo, nombre, descripcion, sector, calificacion_promedio, destacado, activo, categoria_id, fecha_inicio, fecha_fin, url_imagen) VALUES ('Evento', 'Fiesta de la Virgen del Quinche', 'Peregrinación y festividades religiosas tradicionales.', 'El Quinche', 4.9, 1, 1, (SELECT id FROM categoria WHERE nombre='Tradiciones' AND tipo='Cultural' LIMIT 1), '2026-11-15', '2026-11-21', 'https://www.turisec.com/wp-content/uploads/2022/11/peregrinacion.jpg'), ('Evento', 'Concierto de la Orquesta Sinfónica', 'Temporada de conciertos en el Teatro Sucre.', 'Teatro Sucre', 4.8, 0, 1, (SELECT id FROM categoria WHERE nombre='Música' AND tipo='Cultural' LIMIT 1), '2026-08-18', '2026-08-18', 'https://cdn.teatrosucre.com/wp-content/uploads/2025/04/21104323/Banda-Sinfonica-Metropolitana-de-Quito-1-1024x683.jpg'), ('Evento', 'Festival de la Luz', 'Proyecciones artísticas sobre las fachadas del Centro Histórico.', 'Centro Histórico', 4.9, 1, 1, (SELECT id FROM categoria WHERE nombre='Arte' AND tipo='Cultural' LIMIT 1), '2026-08-09', '2026-08-13', 'https://imagenes.elpais.com/resizer/v2/YO2VUTNST5KQNMFHYXQVGM2PQE.jpg?auth=6db3595b934917799e6f727be2a5e226d12a362f99479105a7c83eda2d7fdd68&width=1200');